# Generated by Django 5.2 on 2025-11-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_booking_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
