# Generated by Django 5.2 on 2025-09-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_booking_remove_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='moyasar_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
