# Generated by Django 5.2 on 2025-09-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_moyasar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='moyasar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
