# Generated by Django 5.2 on 2025-07-14 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='ServiceImages/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='ServiceImages/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='ServiceImages/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('servicecard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourapp.servicecard')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('NumofAdult', models.IntegerField()),
                ('date', models.DateField()),
                ('totalprice', models.IntegerField()),
                ('pickup', models.CharField()),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
                ('dropoff', models.CharField(default="I don't need")),
                ('policy', models.BooleanField(default=True)),
                ('servicebooking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourapp.servicebooking')),
            ],
        ),
    ]
