# Generated by Django 5.2.4 on 2025-07-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='image1_cloudinary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='image2_cloudinary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='image3_cloudinary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='video_cloudinary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
