# Generated by Django 5.2 on 2025-07-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0002_servicebooking_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecard',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
