# Generated by Django 5.2.4 on 2025-07-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0002_servicebooking_image1_cloudinary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='image1_cloudinary',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='image2_cloudinary',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='image3_cloudinary',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='video',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='video_cloudinary',
        ),
        migrations.RemoveField(
            model_name='servicecard',
            name='image',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='image1_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='image2_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='image3_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='exclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='included',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
