# Generated by Django 5.2 on 2025-07-14 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0003_servicecard_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='servicecard',
        ),
        migrations.AddField(
            model_name='servicecard',
            name='servicebooking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourapp.servicebooking'),
        ),
    ]
