# Generated by Django 5.2 on 2025-07-15 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0004_remove_servicebooking_servicecard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='Exclusions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='included',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='period',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
