# Generated by Django 5.2 on 2025-07-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0005_servicebooking_exclusions_servicebooking_included_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='period',
            field=models.IntegerField(),
        ),
    ]
