# Generated by Django 5.2 on 2025-09-23 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='cost',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyasar_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='tourapp.booking')),
            ],
        ),
    ]
