# Generated by Django 5.2 on 2025-07-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0006_alter_servicebooking_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='period',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
