# Generated by Django 5.2 on 2025-07-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0007_alter_servicebooking_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicebooking',
            old_name='Exclusions',
            new_name='Exclusion',
        ),
    ]
