# Generated by Django 5.2 on 2025-09-23 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0007_booking_confirmed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
