# Generated by Django 5.2 on 2025-07-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0008_rename_exclusions_servicebooking_exclusion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicebooking',
            old_name='Exclusion',
            new_name='exclusion',
        ),
    ]
