# Generated by Django 5.2 on 2025-10-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0008_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_price_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Price_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numper_o_p', models.IntegerField()),
                ('total_g', models.IntegerField(blank=True, null=True)),
                ('total_g_d', models.IntegerField(blank=True, null=True)),
                ('total_g_b', models.IntegerField(blank=True, null=True)),
                ('total_g_v', models.IntegerField(blank=True, null=True)),
                ('total_g_d_b', models.IntegerField(blank=True, null=True)),
                ('total_g_d_v', models.IntegerField(blank=True, null=True)),
                ('main_price_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.main_price_model')),
            ],
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='price_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourapp.price_model'),
        ),
    ]
