# Generated by Django 5.2 on 2025-10-11 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0009_main_price_model_price_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='price_model',
        ),
        migrations.AddField(
            model_name='booking',
            name='bus_type',
            field=models.CharField(choices=[('none', 'private car '), ('normal', 'normal bus'), ('vip', ' VIP')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='include_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='main_price_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourapp.main_price_model'),
        ),
        migrations.CreateModel(
            name='BookingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourapp.booking')),
            ],
        ),
    ]
