# Generated by Django 5.2 on 2025-07-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0009_rename_exclusion_servicebooking_exclusion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_number',
            new_name='hotel',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(),
        ),
    ]
