# Generated by Django 5.2.4 on 2025-10-11 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0010_remove_servicebooking_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingprice',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='tourapp.booking'),
        ),
    ]
