# Generated by Django 5.2 on 2025-07-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0010_rename_room_number_booking_hotel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='NumofAdult',
            new_name='numofadult',
        ),
    ]
