# Generated by Django 5.2 on 2025-07-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0011_rename_numofadult_booking_numofadult'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
