# Generated by Django 5.2 on 2025-07-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0012_servicebooking_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('tour_date', models.DateField()),
                ('num_people', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
