# Generated by Django 5.2 on 2025-11-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0012_alter_review_options_review_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='confirmed',
        ),
    ]
