# Generated by Django 5.2 on 2025-11-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0013_remove_booking_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
