# Generated by Django 5.2 on 2025-07-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0013_tourrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='disease',
            field=models.CharField(blank=True, null=True),
        ),
    ]
