# Generated by Django 5.2 on 2025-07-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0014_booking_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='totalprice',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='servicecard',
            name='price',
        ),
    ]
