# Generated by Django 5.2 on 2026-01-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0014_booking_created_at_booking_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecard',
            name='intial_price',
            field=models.IntegerField(default=0),
        ),
    ]
