# Generated by Django 5.2.4 on 2025-07-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0015_remove_booking_totalprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='disease',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropoff',
            field=models.CharField(default="I don't need", max_length=50),
        ),
    ]
