# Generated by Django 5.2 on 2026-01-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0015_servicecard_intial_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecard',
            old_name='intial_price',
            new_name='initial_price',
        ),
    ]
